version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  assignees:
  - goloroden
  labels:
  - Dependencies
  allow:
  - dependency-type: direct
  commit-message:
    prefix: chore
    prefix-development: chore

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  assignees:
  - goloroden
  labels:
  - Dependencies
  commit-message:
    prefix: chore
